version: '3.8'
services:
  dev-db:
    image: postgres:14
    container_name: dev-db
    ports:
      - "${POSTGRES_DB_PORT_DEV}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - ./postgresql_dev_db:/var/lib/postgresql/data
    networks:
      - nest
  test-db:
    image: postgres:14
    container_name: test-db
    ports:
      - "${POSTGRES_DB_PORT_TEST}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - ./postgresql_test_db:/var/lib/postgresql/data
    networks:
      - nest
networks:
  nest:
