version: '3.8'
services:
  dev-db:
    image: postgres:14
    container_name: dev-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist
    networks:
      - nest
networks:
  nest:
